### ISSUE TITLE
Issue : While Loading Modal in Line no 106

### ISSUE THREAD

**Issue by kaniket7209** [hassancs91/ImageBackgroundRemover#1]
Hey can You please help me out doing this setup as I m facing issues setting it up because of modal // It fails loading the modal as the path which is mentioned there (.pth) is not present in saved modals section so pls help me out

**Comment by hassancs91** [comment]
HI friend, the model size is big. This is why I mention another download link to get the modal. Check it here
https://learnwithhasan.com/python-image-background-remover/

**Comment by DevDianDankie** [comment]
Page not found :(

**Comment by hassancs91** [comment]
Fixed

**Comment by Arsalan66** [comment]
Sir, I cannot find the model that you have pasted the link on github

**Comment by hassancs91** [comment]
Hi, download from this link: https://learnwithhasan.com/python-image-background-remover/

**Comment by Arsalan66** [comment]
Thanks sir, I got the link of your model.
