### ISSUE TITLE
(cv2, skimage, transform, io, PIL, Image)  I cannot install these packages.

### ISSUE THREAD

**Issue by TinkuMajhi** [hassancs91/ImageBackgroundRemover#3]
(cv2, skimage, transform, io, PIL, Image) I cannot install these packages. These are not mentioned in the requairment.txt file. Can you help me

**Comment by DevDianDankie** [comment]
I got it working by:

- Installing https://pypi.org/project/opencv-python/ instead of cv2

- Installing the suggested package by pip when skimage failed to install
 
- and also it did not want to work from within vs code. Had to run python __init__.py in directory with windows cmd
